### PR TITLE
inseri-arquivos

### PR DESCRIPTION
**Pull request by janaynacortez**
POR FAVOR, EDITE ESSA MENSAGEM INSERINDO AS INFORMAÇÕES DO SEU PROJETO. COMECE APAGANDO ESSA LINHA.

### O que funciona
- DESCREVA O QUE FUNCIONA NO SEU PROJETO

### O que não funciona
- DESCREVA O QUE NÃO FUNCIONA NO SEU PROJETO

### Link Surge 
A PARTIR DA SEMANA 5, INSIRA AQUI O LINK DO SURGE. **ANTES DISSO, APAGUE ESSAS DUAS LINHAS.**

### Imagens
TIRE PRINTS DAS TELAS DO SEU SITE E COLE AQUI

### CODE REVIEW

**Comment by janaynacortez** [comment]
[redes-sociais.txt](https://github.com/future4code/hooks-Janayna-Cortez/files/8024715/redes-sociais.txt)

**Comment by janaynacortez** [comment]
[bio.txt](https://github.com/future4code/hooks-Janayna-Cortez/files/8024724/bio.txt)

**Comment by janaynacortez** [comment]
[comida.txt](https://github.com/future4code/hooks-Janayna-Cortez/files/8024729/comida.txt)

**Comment by janaynacortez** [comment]
[filmes.txt](https://github.com/future4code/hooks-Janayna-Cortez/files/8024730/filmes.txt)

**Comment by janaynacortez** [comment]
[musicas.txt](https://github.com/future4code/hooks-Janayna-Cortez/files/8024734/musicas.txt)

**Review by janaynacortez — COMMENTED** [review]
alteração arquivo bio.txt

**Comment by janaynacortez** [comment]
[comida.txt](https://github.com/future4code/hooks-Janayna-Cortez/files/8024893/comida.txt)

**Comment by janaynacortez** [comment]
[filmes.txt](https://github.com/future4code/hooks-Janayna-Cortez/files/8024904/filmes.txt)

**Review by helanymelo — APPROVED** [review]

**Pull request merged**
